name: Say Hello


on:
  push:
    branches: 
      - master

jobs: 
  hello_world:
    runs-on: ubuntu-20.04  
    steps:
      - name: print message
        run: echo "Hello world"
      - name: Date
        run: date 
      - run: ls -l
